# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sune Mølgaard Laursen
tagline:          
description:      'Personal Website'
url:              http://smlaursen.github.io/
baseurl:          /
email:		      Sune1987@gmail.com
github_username:      SMLaursen
linkedin_username:    SuneLaursen

author:
  name:           Sune Mølgaard Laursen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SMLaursen
